### ISSUE TITLE
Only send focus escape sequences to vim

### ISSUE THREAD

**Issue by trygveaa** [amerlyq/urxvt-ext-evolved#1]
Do you know if it would be possible to only send the escape sequences for focus in and out when vim is open in the terminal, and if so how?

I'm asking because I experience some problems with these being sent when not in vim:
 - The bell is triggered when focus is lost. I have "URxvt.urgentOnBell: true" in .Xresources. This makes the window get the urgent hint for a short while when the window lose focus (sometimes, the hint sticks until I focus the window again).
 - When enabled on start (by putting the enable command in .bashrc), "^[[I" is printed to the terminal before by promt when opening urxvt. Increasing the sleep in on_focus_in makes this happen less often.
 - When using a program that uses stdin and inputing directly from the terminal (e.g. when running just cat), the escape sequences are printed in the terminal when focus is gained or lost.

Other solutions to these problems would also be very welcome.

**Comment by amerlyq** [comment]
Protocol for terminal focus works in documented way: you request to receive events and only after that you will receive them. Each terminal application must decide to receive those events by itself. So if you don't want them -- don't do silly things and don't place activation escape sequences anywhere permanent. Plugin ```vim-focus-autocmd``` was supposed to solve exactly that problem -- it requests focus events on ```VimEnter``` and drops subscription on ```VimLeave```. Therefore focus events works in vim only.
All your other problems (and many more which not bited you yet) are direct consequences of inappropriate usage.

**Comment by amerlyq** [comment]
By "documented" I mean implementation in ```XTerm``` and its approved standards.
I must have somewhere in one of ```*.otl``` files inside ```urxvt-ext-evolved``` or ```vim-focus-autocmd``` link to appropriate docs. Check it if you feel that way.

**Comment by trygveaa** [comment]
Aha, thanks for clarifying. The reason I put it in .bashrc was that vim-focus-autocmd didn't seem to work without it. I found out now that this was because TERM was set incorrectly in my terminal.

**Comment by amerlyq** [comment]
By the way, I refactored vim-focus-autocmd. So try it out and tell if some
bugs present, when you have mood. Because it don't work in current neovim
with broken t_ti and I can't test it thoroughly.
